# MultiLayer Perceptron

# LAB WORK

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.InteractiveSession()

In [3]:
#Defining tensors


In [4]:
a=tf.zeros((2,2))
b=tf.ones((2,3))

In [5]:
a.eval()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [6]:
b.eval()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [7]:
tf.reduce_sum(b,reduction_indices=1).eval()

array([3., 3.], dtype=float32)

In [8]:
tf.reduce_sum(b,reduction_indices=0).eval()
#0 is for coulmn wise and 1 is for row wise

array([2., 2., 2.], dtype=float32)

In [9]:
#Getting shape of variable
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [10]:
#Reshaping the tensor
tf.reshape(a,(1,4)).eval()

array([[0., 0., 0., 0.]], dtype=float32)

In [11]:
#Explicit evaluation in tensorflow 
ta=tf.zeros((2,2))
print(ta)

Tensor("zeros_1:0", shape=(2, 2), dtype=float32)


In [12]:
print(ta.eval())

[[0. 0.]
 [0. 0.]]


In [15]:
a=np.zeros((2,2))
print(a)
#Tensor wil not evaluate till you ask for it where as numpy will do the operation

[[0. 0.]
 [0. 0.]]


In [16]:
#Defining the constant
a=tf.constant(1)
b=tf.constant(2)
c=a*b


In [17]:
c.eval()

2

In [18]:
with tf.Session() as sess:
    print(c.eval())
    print(sess.run(c))

2
2


In [19]:
#Defining variables
w=tf.ones((2,2),name="Weight")

In [20]:
w.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [24]:
#Initialising variable after invoking session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(w))

[[1. 1.]
 [1. 1.]]


In [26]:
#defining variable with random normal
nw=tf.Variable(tf.random_normal((2,2),name="random_weight"))

In [27]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(nw))

[[ 0.36749223 -1.286126  ]
 [-0.3935514   1.0600538 ]]


In [28]:
#TensorFlow State Update

In [29]:
var_1=tf.Variable(0,name="var_1")
ass_op=tf.add(var_1,tf.constant(1))
ass_upd=tf.assign(var_1,ass_op)

In [35]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        print(sess.run(ass_upd))

1
2
3
4
5


In [47]:
#Displaying The TensorFlow Variable State
x=tf.constant(1)
y=tf.constant(5)
z=tf.constant(7)
mul_x_y=x*y
final_op=x*y+z
with tf.Session() as sess:
    print(sess.run([mul_x_y,final_op]))

[5, 12]


In [45]:
#Converting a Numpy array to Tensor
a=np.zeros((2,2))
b=tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(b))

[[0. 0.]
 [0. 0.]]


In [51]:
#Placeholder and Feed Dictionary
inp1=tf.placeholder(tf.float32,shape=(1,2))
inp2=tf.placeholder(tf.float32,shape=(2,1))
output=tf.matmul(inp1,inp2)
with tf.Session() as sess:
    print(sess.run([output],feed_dict={inp1:[[1,3]],inp2:[[2],[3]]}))

[array([[11.]], dtype=float32)]


In [62]:
#XOR implementation in TensorFlow with linear Activation
X_=tf.placeholder(tf.float32,shape=[4,2],name="x-input")
Y_=tf.placeholder(tf.float32,shape=[4,1],name="y-input")
#Random weights
w1=tf.Variable(tf.random_uniform([2,2],-1,1),name="weights1")
w2=tf.Variable(tf.random_uniform([2,1],-1,1),name="weights2")
#Bias to hidden and output layer respectively
b1=tf.Variable(tf.zeros([2]),name="Bias1")
b2=tf.Variable(tf.zeros([1]),name="Bias2")
#Define the final output through final pass
z2=tf.matmul(X_,w1)+b1
pred=tf.sigmoid(tf.matmul(z2,w2)+b2)

#Define the CRoss-entropy
cost=tf.reduce_mean(((Y_*tf.log(pred))+((1-Y_)*tf.log(1-pred)))*-1)
learning_rate=0.01
train_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
XOR_X=[[0,0],[0,1],[1,0],[1,1]]
XOR_Y=[[0],[1],[1],[0]]

init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
for i in range(100000):
    sess.run(train_step,feed_dict={X_:XOR_X,Y_:XOR_Y})
    if(i%10000==0):
        print('Epoch',i)
        print('Prediction',sess.run(pred,feed_dict={X_:XOR_X,Y_:XOR_Y}))
        print('Weight from input to hidden layer:',sess.run(w1))
        print('Bias in the hidden layer:',sess.run(b1))
        print('Weight from hidden to output layer',sess.run(w2))
        print('Bias in the output layer',sess.run(b2))
        print('Cost',sess.run(cost,feed_dict={X_:XOR_X,Y_:XOR_Y}))
print('Final Prediction',sess.run(pred,feed_dict={X_:XOR_X,Y_:XOR_Y}))

Epoch 0
Prediction [[0.500934  ]
 [0.3270511 ]
 [0.37569466]
 [0.22563025]]
Weight from input to hidden layer: [[-0.9797762   0.27926224]
 [-0.68747395 -0.17974493]]
Bias in the hidden layer: [0.00115568 0.00140522]
Weight from hidden to output layer [[0.800073  ]
 [0.97504616]]
Bias in the output layer [0.0014413]
Cost 0.761835
Epoch 10000
Prediction [[0.50003254]
 [0.49996984]
 [0.5000389 ]
 [0.49997628]]
Weight from input to hidden layer: [[-0.8923571   0.40418777]
 [-0.45855558  0.20744216]]
Bias in the hidden layer: [ 0.02204675 -0.00655632]
Weight from hidden to output layer [[0.46332493]
 [1.0229819 ]]
Bias in the output layer [-0.00337766]
Cost 0.69314724
Epoch 20000
Prediction [[0.5000001 ]
 [0.4999972 ]
 [0.5000028 ]
 [0.49999988]]
Weight from input to hidden layer: [[-0.8923571   0.40415263]
 [-0.45848435  0.20763278]]
Bias in the hidden layer: [ 0.02202008 -0.00661465]
Weight from hidden to output layer [[0.46330112]
 [1.0229819 ]]
Bias in the output layer [-0.00343475]
Cos

In [64]:
#XOR implementation in TensorFlow with linear Activation
X_=tf.placeholder(tf.float32,shape=[4,2],name="x-input")
Y_=tf.placeholder(tf.float32,shape=[4,1],name="y-input")
#Random weights
w1=tf.Variable(tf.random_uniform([2,2],-1,1),name="weights1")
w2=tf.Variable(tf.random_uniform([2,1],-1,1),name="weights2")
#Bias to hidden and output layer respectively
b1=tf.Variable(tf.zeros([2]),name="Bias1")
b2=tf.Variable(tf.zeros([1]),name="Bias2")
#Define the final output through final pass
z2=tf.sigmoid(tf.matmul(X_,w1)+b1)
pred=tf.sigmoid(tf.matmul(z2,w2)+b2)

#Define the CRoss-entropy
cost=tf.reduce_mean(((Y_*tf.log(pred))+((1-Y_)*tf.log(1-pred)))*-1)
learning_rate=0.01
train_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
XOR_X=[[0,0],[0,1],[1,0],[1,1]]
XOR_Y=[[0],[1],[1],[0]]

init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
for i in range(100000):
    sess.run(train_step,feed_dict={X_:XOR_X,Y_:XOR_Y})
    if(i%10000==0):
        print('Epoch',i)
        print('Prediction',sess.run(pred,feed_dict={X_:XOR_X,Y_:XOR_Y}))
        print('Weight from input to hidden layer:',sess.run(w1))
        print('Bias in the hidden layer:',sess.run(b1))
        print('Weight from hidden to output layer',sess.run(w2))
        print('Bias in the output layer',sess.run(b2))
        print('Cost',sess.run(cost,feed_dict={X_:XOR_X,Y_:XOR_Y}))
print('Final Prediction',sess.run(pred,feed_dict={X_:XOR_X,Y_:XOR_Y}))

Epoch 0
Prediction [[0.33523998]
 [0.32722583]
 [0.34532282]
 [0.3337777 ]]
Weight from input to hidden layer: [[-0.91993254  0.35277775]
 [-0.6715703   0.62016857]]
Bias in the hidden layer: [-0.0002096  -0.00033556]
Weight from hidden to output layer [[-0.5449369]
 [-0.8277217]]
Bias in the output layer [0.00165182]
Cost 0.74871033
Epoch 10000
Prediction [[0.4075511 ]
 [0.51224875]
 [0.52471954]
 [0.5444505 ]]
Weight from input to hidden layer: [[-1.7742009   0.25375876]
 [-1.7084173   0.5351718 ]]
Bias in the hidden layer: [-0.18927172 -0.2023458 ]
Weight from hidden to output layer [[-1.5414602]
 [-0.5565537]]
Bias in the output layer [0.57412845]
Cost 0.65589446
Epoch 20000
Prediction [[0.18182543]
 [0.58804154]
 [0.60509956]
 [0.5908796 ]]
Weight from input to hidden layer: [[-3.478737    0.60759497]
 [-3.4965231   0.8741699 ]]
Bias in the hidden layer: [ 0.49542657 -0.62226766]
Weight from hidden to output layer [[-3.6541462]
 [-1.1135315]]
Bias in the output layer [1.1555177]
C

In [65]:
#XOR implementation in TensorFlow with linear Activation
X_=tf.placeholder(tf.float32,shape=[4,2],name="x-input")
Y_=tf.placeholder(tf.float32,shape=[4,1],name="y-input")
#Random weights
w1=tf.Variable(tf.random_uniform([2,2],-1,1),name="weights1")
w2=tf.Variable(tf.random_uniform([2,1],-1,1),name="weights2")
#Bias to hidden and output layer respectively
b1=tf.Variable(tf.zeros([2]),name="Bias1")
b2=tf.Variable(tf.zeros([1]),name="Bias2")
#Define the final output through final pass
z2=tf.matmul(X_,w1)+b1
pred=tf.matmul(z2,w2)+b2

#Define the CRoss-entropy
cost=tf.reduce_mean(((Y_*tf.log(pred))+((1-Y_)*tf.log(1-pred)))*-1)
learning_rate=0.01
train_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
XOR_X=[[0,0],[0,1],[1,0],[1,1]]
XOR_Y=[[0],[1],[1],[0]]

init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
for i in range(100000):
    sess.run(train_step,feed_dict={X_:XOR_X,Y_:XOR_Y})
    if(i%10000==0):
        print('Epoch',i)
        print('Prediction',sess.run(pred,feed_dict={X_:XOR_X,Y_:XOR_Y}))
        print('Weight from input to hidden layer:',sess.run(w1))
        print('Bias in the hidden layer:',sess.run(b1))
        print('Weight from hidden to output layer',sess.run(w2))
        print('Bias in the output layer',sess.run(b2))
        print('Cost',sess.run(cost,feed_dict={X_:XOR_X,Y_:XOR_Y}))
print('Final Prediction',sess.run(pred,feed_dict={X_:XOR_X,Y_:XOR_Y}))

Epoch 0
Prediction [[nan]
 [nan]
 [nan]
 [nan]]
Weight from input to hidden layer: [[nan nan]
 [nan nan]]
Bias in the hidden layer: [nan nan]
Weight from hidden to output layer [[nan]
 [nan]]
Bias in the output layer [nan]
Cost nan
Epoch 10000
Prediction [[nan]
 [nan]
 [nan]
 [nan]]
Weight from input to hidden layer: [[nan nan]
 [nan nan]]
Bias in the hidden layer: [nan nan]
Weight from hidden to output layer [[nan]
 [nan]]
Bias in the output layer [nan]
Cost nan
Epoch 20000
Prediction [[nan]
 [nan]
 [nan]
 [nan]]
Weight from input to hidden layer: [[nan nan]
 [nan nan]]
Bias in the hidden layer: [nan nan]
Weight from hidden to output layer [[nan]
 [nan]]
Bias in the output layer [nan]
Cost nan
Epoch 30000
Prediction [[nan]
 [nan]
 [nan]
 [nan]]
Weight from input to hidden layer: [[nan nan]
 [nan nan]]
Bias in the hidden layer: [nan nan]
Weight from hidden to output layer [[nan]
 [nan]]
Bias in the output layer [nan]
Cost nan
Epoch 40000
Prediction [[nan]
 [nan]
 [nan]
 [nan]]
Weight f

In [66]:
#XOR implementation in TensorFlow with linear Activation
X_=tf.placeholder(tf.float32,shape=[4,2],name="x-input")
Y_=tf.placeholder(tf.float32,shape=[4,1],name="y-input")
#Random weights
w1=tf.Variable(tf.random_uniform([2,2],-1,1),name="weights1")
w2=tf.Variable(tf.random_uniform([2,1],-1,1),name="weights2")
#Bias to hidden and output layer respectively
b1=tf.Variable(tf.zeros([2]),name="Bias1")
b2=tf.Variable(tf.zeros([1]),name="Bias2")
#Define the final output through final pass
z2=tf.sigmoid(tf.matmul(X_,w1)+b1)
pred=tf.matmul(z2,w2)+b2

#Define the CRoss-entropy
cost=tf.reduce_mean(((Y_*tf.log(pred))+((1-Y_)*tf.log(1-pred)))*-1)
learning_rate=0.01
train_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
XOR_X=[[0,0],[0,1],[1,0],[1,1]]
XOR_Y=[[0],[1],[1],[0]]

init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
for i in range(100000):
    sess.run(train_step,feed_dict={X_:XOR_X,Y_:XOR_Y})
    if(i%10000==0):
        print('Epoch',i)
        print('Prediction',sess.run(pred,feed_dict={X_:XOR_X,Y_:XOR_Y}))
        print('Weight from input to hidden layer:',sess.run(w1))
        print('Bias in the hidden layer:',sess.run(b1))
        print('Weight from hidden to output layer',sess.run(w2))
        print('Bias in the output layer',sess.run(b2))
        print('Cost',sess.run(cost,feed_dict={X_:XOR_X,Y_:XOR_Y}))
print('Final Prediction',sess.run(pred,feed_dict={X_:XOR_X,Y_:XOR_Y}))

Epoch 0
Prediction [[-0.8600207]
 [-0.8972149]
 [-0.9892044]
 [-1.0290135]]
Weight from input to hidden layer: [[ 0.6115816   0.01284598]
 [-0.22519115  0.40570605]]
Bias in the hidden layer: [0.0016296  0.00165312]
Weight from hidden to output layer [[-0.852893  ]
 [-0.84977627]]
Bias in the output layer [-0.00798739]
Cost nan
Epoch 10000
Prediction [[-23.061796]
 [-23.728092]
 [-23.77331 ]
 [-23.98857 ]]
Weight from input to hidden layer: [[1.4309033  1.0349367 ]
 [0.89365345 1.3009307 ]]
Bias in the hidden layer: [2.6600134 2.6513956]
Weight from hidden to output layer [[-7.8603544]
 [-7.887148 ]]
Bias in the output layer [-8.347948]
Cost nan
Epoch 20000
Prediction [[-33.407806]
 [-33.972115]
 [-33.99873 ]
 [-34.15053 ]]
Weight from input to hidden layer: [[1.5540777 1.1993396]
 [1.0744843 1.437001 ]]
Bias in the hidden layer: [3.2989016 3.2906084]
Weight from hidden to output layer [[-11.2082615]
 [-11.235221 ]]
Bias in the output layer [-11.766725]
Cost nan
Epoch 30000
Prediction 

# HOME ASSIGNMENT

# Implementing AND and OR Function in TensorFlow

## OR FUNCTION WITH TWO INPUTS

In [49]:
#OR implementation in TensorFlow with linear Activation
X_=tf.placeholder(tf.float32,shape=[4,2],name="x-input")
Y_=tf.placeholder(tf.float32,shape=[4,1],name="y-input")
#Random weights
w1=tf.Variable(tf.random_uniform([2,2],-1,1),name="weights1")
w2=tf.Variable(tf.random_uniform([2,1],-1,1),name="weights2")
#Bias to hidden and output layer respectively
b1=tf.Variable(tf.zeros([2]),name="Bias1")
b2=tf.Variable(tf.zeros([1]),name="Bias2")
#Define the final output through final pass
z2=(tf.matmul(X_,w1)+b1)
pred=tf.sigmoid((tf.matmul(z2,w2)+b2))

#Define the Cross-entropy
cost=tf.reduce_mean(((Y_*tf.log(pred))+((1-Y_)*tf.log(1-pred)))*-1)
learning_rate=0.01
train_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
OR_X=[[0,0],[0,1],[1,0],[1,1]]
OR_Y=[[0],[1],[1],[1]]

init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
for i in range(10000):
    sess.run(train_step,feed_dict={X_:OR_X,Y_:OR_Y})
    if(i%10000==0):
        print('Epoch',i)
        print('Prediction',sess.run(pred,feed_dict={X_:OR_X,Y_:OR_Y}))
        print('Weight from input to hidden layer:',sess.run(w1))
        print('Bias in the hidden layer:',sess.run(b1))
        print('Weight from hidden to output layer',sess.run(w2))
        print('Bias in the output layer',sess.run(b2))
        print('Cost',sess.run(cost,feed_dict={X_:OR_X,Y_:OR_Y}))

print('Final Prediction',sess.run(pred,feed_dict={X_:OR_X,Y_:OR_Y}))


Epoch 0
Prediction [[0.50096977]
 [0.41875285]
 [0.46882737]
 [0.38778633]]
Weight from input to hidden layer: [[0.13077278 0.3238582 ]
 [0.29143375 0.9353435 ]]
Bias in the hidden layer: [-0.00143138 -0.00065808]
Weight from hidden to output layer [[-0.46396014]
 [-0.21014829]]
Bias in the output layer [0.00307682]
Cost 0.8175961
Final Prediction [[0.01010965]
 [0.99610883]
 [0.99591905]
 [0.9999999 ]]


## AND FUNCTION WITH THREE INPUTS

In [47]:
#AND implementation in TensorFlow with linear Activation for 
X_=tf.placeholder(tf.float32,shape=[8,3],name="x-input")
Y_=tf.placeholder(tf.float32,shape=[8,1],name="y-input")
#Random weights
w1=tf.Variable(tf.random_uniform([3,2],-1,1),name="weights1")
w2=tf.Variable(tf.random_uniform([2,1],-1,1),name="weights2")
#Bias to hidden and output layer respectively
b1=tf.Variable(tf.zeros([2]),name="Bias1")
b2=tf.Variable(tf.zeros([1]),name="Bias2")
#Define the final output through final pass
z2=(tf.matmul(X_,w1)+b1)
pred=tf.sigmoid((tf.matmul(z2,w2)+b2))

#Define the Cross-entropy
cost=tf.reduce_mean(((Y_*tf.log(pred))+((1-Y_)*tf.log(1-pred)))*-1)
learning_rate=0.01
train_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
AND_X=[[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]
AND_Y=[[0],[0],[0],[0],[0],[0],[0],[1]]

init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
for i in range(100000):
    sess.run(train_step,feed_dict={X_:AND_X,Y_:AND_Y})
    if(i%10000==0):
        print('Epoch',i)
        print('Prediction',sess.run(pred,feed_dict={X_:AND_X,Y_:AND_Y}))
        print('Weight from input to hidden layer:',sess.run(w1))
        print('Bias in the hidden layer:',sess.run(b1))
        print('Weight from hidden to output layer',sess.run(w2))
        print('Bias in the output layer',sess.run(b2))
        print('Cost',sess.run(cost,feed_dict={X_:AND_X,Y_:AND_Y}))

print('Final Prediction',sess.run(pred,feed_dict={X_:AND_X,Y_:AND_Y}))
acc,acc_op=(tf.metrics.accuracy(AND_Y,sess.run(pred,feed_dict={X_:AND_X,Y_:AND_Y})))

Epoch 0
Prediction [[0.49848515]
 [0.4117461 ]
 [0.5546795 ]
 [0.46727288]
 [0.5034611 ]
 [0.4165755 ]
 [0.5595905 ]
 [0.4722307 ]]
Weight from input to hidden layer: [[ 0.66171706  0.37585205]
 [-0.40418205  0.09836131]
 [ 0.8863516  -0.01691118]]
Bias in the hidden layer: [ 0.00137999 -0.00263073]
Weight from hidden to output layer [[-0.38182193]
 [ 0.7251853 ]]
Bias in the output layer [-0.00362482]
Cost 0.6835872
Epoch 10000
Prediction [[1.0028595e-07]
 [5.3218355e-05]
 [5.3152675e-05]
 [2.7435387e-02]
 [5.3229673e-05]
 [2.7474055e-02]
 [2.7441073e-02]
 [9.3739730e-01]]
Weight from input to hidden layer: [[ 0.4734074   1.5434515 ]
 [-0.58992654  1.4160244 ]
 [ 0.58994836  1.5573295 ]]
Bias in the hidden layer: [ 0.75863177 -3.2590213 ]
Weight from hidden to output layer [[-0.50433546]
 [ 4.219864  ]]
Bias in the output layer [-1.9800092]
Cost 0.018538712
Epoch 20000
Prediction [[2.9461139e-10]
 [1.6186513e-06]
 [1.6175957e-06]
 [8.8091353e-03]
 [1.6185617e-06]
 [8.8143414e-03]
 [8.

## Observation

While trying with different types of inputs, increasing epochs gave good result 
but it reaches a saturation point aftre which the neurons donot further update weights